server:
  port: 9998

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/
        
spring:
  application:
      name: api-gateway-service
  cloud: 
   gateway:
    discovery:
        locator:
            enabled: true

    routes:
      - id: product_service_v1
        uri: 'http://localhost:8081'
        predicates:
          - Path=/product/**
          - Query=src,mobile
      - id: account_microservice
        uri: lb://account-microservice
        predicates:
          - Path=/account/**